apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter-daemonset
  labels:
    app: node-exporter-ds
spec:
  selector:
    matchLabels:
      app: node-exporter-ds
  template:
    metadata:
      labels:
        app: node-exporter-ds
    spec:
      hostNetwork: true # Usar rede do host
      containers:
        - name: node-exporter
          image: prom/node-exporter:v1.4.1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
          ports:
            - containerPort: 9100
              hostPort: 9100
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly: true
            - name: sys
              mountPath: /host/sys
              readOnly: true
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
      tolerations:
        - operator: "Exists"
      terminationGracePeriodSeconds: 30
